version: '3.4'

services:
  app:
    image: i24-bo:app-dev
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
      target: dev
    command: yarn start
    tty: true
    volumes:
      - ./../:/app
    ports:
      - published: 5000
        target: 3000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 800M

  server:
    image: i24-bo:server-dev
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
      target: dev
    command: yarn start
    tty: true
    volumes:
      - ./../server/:/app
    ports:
      - published: 5001
        target: 3001
        protocol: tcp
        mode: host        
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  test:
    image: i24-bo:test-dev
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
      target: dev
    command: 'yarn test'
    tty: true
    environment:
      - NODE_ENV=test
    volumes:
      - ./../:/app
    deploy:
      # scale it up to run the tests on your dev machine or use docker-compose
      # to run this service
      replicas: 0
      restart_policy:
        condition: 'none'
