version: '3.4'

services:
  app:
    image: knp-te:app-dev
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev
    command: yarn start
    tty: true
    volumes:
      - ./../front/:/app
    ports:
      - published: 5000
        target: 3000
        protocol: tcp
        mode: host

  server:
    image: knp-te:server-dev
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev
    command: yarn start
    tty: true
    volumes:
      - ./../server/:/app
    ports:
      - published: 5001
        target: 3001
        protocol: tcp
        mode: host
